### PR TITLE
#16 allow case override at individual TokenType level

### PR DESCRIPTION
**Pull request by triwav**
This is the implementation for https://github.com/TwitchBronBron/brightscript-formatter/issues/16. In my config I have:
```
"brightscript.format.keywordCaseOverride": {
        "string": "title",
        "float": "title",
        "double": "title",
        "object": "title",
        "boolean": "title",
        "dynamic": "title",
        "integer": "title"
},
```
and all seems to be working well. Let me know if you see any problems or if I did something wrong. Thanks.

This PR relies on https://github.com/TwitchBronBron/brightscript-formatter/pull/17 for updates in the formatter.

### CODE REVIEW

**Comment by TwitchBronBron** [comment]
@triwav brightscript-formatter@1.5.0 includes the necessary change. Can you update your to include that new version?

**Comment by triwav** [comment]
@TwitchBronBron updated to 1.5.0 and realized I'd accidentally messed up brightscript.format.compositeKeywords so reverted that. Tested and seems to be working well.

**Comment by TwitchBronBron** [comment]
Everything looks good. Thanks for your work on this!

**Comment by TwitchBronBron** [comment]
This got deployed in version 1.3.1. Take a look and let me know if that works for you!

**Comment by triwav** [comment]
Working great. Thanks!

**Comment by TwitchBronBron** [comment]
Oh good! Thanks for the quick turnaround on the testing!

**Pull request merged**
