### PR TITLE
additional brightscript navigation features

### PR DESCRIPTION
**Pull request by georgejecook**
Hi, here's a preliminary PR so you can try out the language features for yourself.

- adds declarations and symbols
- adds go to definition support
- adds command to jump between xml and brs files
- adds placeholder for completion

Please note - I formatted extension.ts (by accident); but I figured  I'll leave it as is, as it's more consistent : I can back it out if needs be.

Fire it up, press APPLE+SHIFT+O, to view symbols in file APPLE-T for whole project, and F12 to go to defintion.
Also find command to switch between xml and brs files - you can assign a hotkey to Brightscript: Toggle xml/brs

### CODE REVIEW

**Comment by TwitchBronBron** [comment]
It looks like the go to definition for functions is offset by 1 character. 

    sub Main()
        DoSomething()
    end sub

    function DoSomething()

    end function


image

image

It misses the "D" and includes the "("

**Comment by georgejecook** [comment]
Ok. I understood the issue now and it’s resolved.

Note - this is all WIP. It’d be good to know how/when you plan to update
your plugin to include these changes and perhaps plan some cadence for
updates?

I have a couple of features I want to add:

1. Go to implementation or peek m.top.fields
2. Support in xml documents, to go to definition for on change handlers
3. Support in brs document, to go to definition of xml field values
4. Add symbol in scope to the completions
5. Display comments associated with a function for all completions

I reckon I can add 1, 2 and possibly 3 this week.. 4 and 5 within a few
weeks. Hopefully, now that you have code to play with, you might also find
some joy in hacking around and building on the existing features.

I’d like to let people know about these updates on the slack group and the
roku forum as well - now that you’ve been using it, as I have for a few
days, I’m sure you’ll concern it’s extremely productive to have these
features. I don’t want/need any recognition or to be making official
announcements for your plugin (though I have praised it highly in the roku
dev’s slack group); however, I’d like to know that these changes are going
to get in peoples hands, and how to broadcast that news : I think it’s
worth making noise about.

thoughts?


On November 18, 2018 at 4:08:05 PM, Bronley Plumb (notifications@github.com)
wrote:

It looks like the go to definition for functions is offset by 1 character.

sub Main()
    DoSomething()
end sub

function DoSomething()

end function

[image: image]
<https://user-images.githubusercontent.com/2544493/48678049-f3ca5c00-eb4b-11e8-987b-1bb5bdbe571e.png>

[image: image]
<https://user-images.githubusercontent.com/2544493/48678055-093f8600-eb4c-11e8-9f5f-8d2ac76f3f8e.png>

It misses the "D" and includes the "("

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TwitchBronBron/vscode-brightscript-language/pull/9#issuecomment-439725975>,
or mute the thread

**Comment by TwitchBronBron** [comment]
> It’d be good to know how/when you plan to update
your plugin to include these changes and perhaps plan some cadence for
updates?

I'm open to some type of weekly/semi-weekly/monthly release cadence (obviously skipping any of those iterations that haven't had changes). However, since this is a lower-key project, I would think getting releases out as soon as new features arrive would be more preferable? 

In general, I wouldn't see any benefit in hoarding changes and pushing off releases. I usually try to release whenever a new feature arrives in master. I already have the build process set up to auto-release whenever I tag master, so releasing is easy. The biggest concern is that we don't push out buggy/incomplete code. If we meet that goal, I'm open to suggestions on release schedules/styles/etc. 

I do value my time with family and extra-curriculars, and I can't work on this project during working hours, but I definitely have a few free hours every week where I could handle PRs and releases and such. 

Thoughts?

**Comment by TwitchBronBron** [comment]
@georgejecook I had a question about the `Toggle xml/brs` feature. I'm not sure the feature works for all scenarios. Take this file for example: 

    
    <component name="Component1" extends="Group" initialFocus="Buttons">
      <children>  ...  </children>
      <script type="text/brightscript" uri="pkg:/components/Common/StandardComponent.brs" />
    </component>
    
    
    <component name="Component2" extends="Group" initialFocus="Buttons">
      <children>  ...  </children>
      <script type="text/brightscript" uri="pkg:/components/Common/StandardComponent.brs" />
    </component>

Both component xml files reference the same `StandardComponent.brs` script, and this is totally legal brightscript, and is a scenario I could see happening in the wild. 

It appears that your action only works when the xml and brs component files are named the same (and in the same folder?). I just wanted to get your explanation for this feature and whether my above situation is a concern?

**Comment by georgejecook** [comment]
I was hoping you'd say that. Family and other obligations and full time
work here too so flexibility to work whenever and know that you'll just
release stuff when youre happy is reassuring.

**Comment by georgejecook** [comment]
Yes, only supports same file name in same folder, at this point.

That’s what I refer to (in xaml/flex parlance) as a codebehind file. I’m an
MVVM programmer (I have a wip MVVM and binding framework for roku, too),
and it’s bad practice to separate give different names/paths to the view
and codebehind.

So, I’ve catered to that pattern first, as it’s the most likely case for
both MVVM and non-MVVM programmers. If people need something else they can
contribute some config that works for them, right? But then it start’s
getting more complicated. Many times there’s multiple imports.. how does
one designate the code behind file? The point is to quickly navigate
between a view and the code for that view..

I do have plans for better support for the notion of scope (i.e. use the
completion to ascertain what methods are in scope in a given file base on
it’s imports); but this is a different feature.


On November 18, 2018 at 10:59:22 PM, Bronley Plumb (notifications@github.com)
wrote:

It appears that your action only works when the xml and brs component files
are named the same (and in the same folder?). I just wanted to get your
explanation for this feature and whether my above situation is a concern?

**Comment by TwitchBronBron** [comment]
@georgejecook can you resolve the merge conflicts for this PR?

**Comment by georgejecook** [comment]
Yes. done!

Please also note I’ve disabled the completion support right now - it get’s
rid of the default text completion - it was just an experiment, which I
thought was unobtrusive; but it’s evidently not.

However, I've left the code in there, commented out as a placeholder, which
might hopefully attract other contributors - if not, I will be adding to it
in due course - hopefully within 2 weeks.

On November 19, 2018 at 3:56:17 PM, Bronley Plumb (notifications@github.com)
wrote:

@georgejecook <https://github.com/georgejecook> can you resolve the merge
conflicts for this PR?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TwitchBronBron/vscode-brightscript-language/pull/9#issuecomment-440038751>,
or mute the thread

**Comment by TwitchBronBron** [comment]
Sounds good. Looks like there's a tslint error failing the build as well. Once you get all of the checks passing, I'm good with this merging into master.

**Comment by georgejecook** [comment]
done


On November 19, 2018 at 4:05:22 PM, Bronley Plumb (notifications@github.com)
wrote:

Sounds good. Looks like there's a tslint error failing the build as well.
Once you get all of the checks passing, I'm good with this merging into
master.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TwitchBronBron/vscode-brightscript-language/pull/9#issuecomment-440041304>,
or mute the thread

**Comment by georgejecook** [comment]
I’ve pushed a second commit. I agree it’s weird - it was passing linking
for me; but is clearly a failure.



On November 19, 2018 at 4:28:37 PM, Bronley Plumb (notifications@github.com)
wrote:

Weird, I just reran the Travis build and it seems like the issue is still
there. :/ It's dying on this line
<https://github.com/TwitchBronBron/vscode-brightscript-language/commit/8ce91553ed8a247adb25a3d084b44512ae74af12#diff-86d4cdd9fe3c74dba8a1a46e247dbd69R38>
.

I wonder if it has something to do with you using force-push
<https://i.chzbgr.com/full/4599061248/h33604441/>? I will always squash all
commits in a PR into a single commit, so perhaps try just pushing a second
commit?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TwitchBronBron/vscode-brightscript-language/pull/9#issuecomment-440047660>,
or mute the thread

**Comment by georgejecook** [comment]
I also, oddly get this problem from tslint from the IDE; but not from npm
run..




On November 19, 2018 at 4:48:21 PM, George Cook (george@tantawowa.com)
wrote:

I’ve pushed a second commit. I agree it’s weird - it was passing linking
for me; but is clearly a failure.



On November 19, 2018 at 4:28:37 PM, Bronley Plumb (notifications@github.com)
wrote:

Weird, I just reran the Travis build and it seems like the issue is still
there. :/ It's dying on this line
<https://github.com/TwitchBronBron/vscode-brightscript-language/commit/8ce91553ed8a247adb25a3d084b44512ae74af12#diff-86d4cdd9fe3c74dba8a1a46e247dbd69R38>
.

I wonder if it has something to do with you using force-push
<https://i.chzbgr.com/full/4599061248/h33604441/>? I will always squash all
commits in a PR into a single commit, so perhaps try just pushing a second
commit?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TwitchBronBron/vscode-brightscript-language/pull/9#issuecomment-440047660>,
or mute the thread

**Comment by georgejecook** [comment]
Looks like it's all passing now. I see coverage is not a failure, which is good, because getting coverage on these is gonna take time...

**Comment by TwitchBronBron** [comment]
I didn't start with coverage, so yeah, it's gonna take some time. But we'll get there eventually. I think that my current policy will be "you can't decrease coverage percentage", but I might even push for "you must increase the coverage percentage by just a little bit on each PR. I'll see how it goes. I'd rather get new features right now and worry about coverage later...but then when you do enforce it, right? :D

**Pull request merged**
