### PR TITLE
Feature/variable panel

### PR DESCRIPTION
**Pull request by chrisdp**

### CODE REVIEW

**Comment by chrisdp** [comment]
#74 relates to this issue

**Comment by georgejecook** [comment]
had a quick look at this, and it seems great - didn't cause me any problems : May I suggest a setting flag to turn it on or off though, in case it causes crashes/hangs in some scenarios?

**Comment by chrisdp** [comment]
Sure. I’ll add that this morning.

**Comment by TwitchBronBron** [comment]
Everything looks good here. I'm fine with the changes. @georgejecook can you give your final "ok" before I merge? I'm accepting the PR as is, with the decrease in unit test coverage, because the majority of the telnet and debugger stuff are VERY hard to test, and it's not worth the effort at this point.

**Comment by georgejecook** [comment]
pulled down. works perfectly both enabled and disabled on 2 very large prod apps

**Pull request merged**
